id: verify_code_change
learningObjectives:
  - Experience the CI/CD process with GitHub Actions
hints:
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Now that you have changed the code, let's see it.
          - text: Keep an eye on the [GitHub Actions workflow](${user.repository}/actions/workflows/deploy.yml) to see when the deployment is finished.
          - text: Once the deployment is finished, go to the same URL from before and see the background color change.
          - text: Let me know when you are ready to continue.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: lucca
          messages:
            - text: "Awesome! You did it."
            - text: "You've just completed the Mastering Continuous Delivery with GitHub Actions quest—great job! In this quest, you set up automated build and deployment workflows using GitHub Actions, enabling continuous delivery of your application."
            - text: "Next, to strengthen your skills and apply them more confidently, here's a personalized learning path:"
            - text: "👉 GitHub Skills: [Deploy to Azure](https://github.com/skills/deploy-to-azure) — practice the next logical GitHub skill."
            - text: "👉 Microsoft Learn: [Build and deploy applications to Azure by using GitHub Actions](https://learn.microsoft.com/en-us/training/modules/github-actions-cd/) — deepen your conceptual understanding."
            - text: "👉 Microsoft Applied Skills: [GitHub Actions Certification Exam](https://learn.microsoft.com/en-us/credentials/certifications/github-actions/) — earn a credential that shows what you've learned."
      - actionId: finish_step
