id: verify_code_change
learningObjectives:
  - Experience the CI/CD process with GitHub Actions
hints:
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Now that you have changed the code, let's see it.
          - text: Keep an eye on the [GitHub Actions workflow](${user.repository}/actions/workflows/deploy.yml) to see when the deployment is finished.
          - text: Once the deployment is finished, go to the same URL from before and see the background color change.
          - text: Let me know when you are ready to continue.
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: lucca
          messages:
            - text: "Awesome! You did it."
            - text: "You've just completed the Mastering Continuous Delivery with GitHub Actions quest—great job! This experience helped you set up automated build and deployment workflows, empowering you to achieve continuous delivery with GitHub Actions."
            - text: "🧠 What's Next?"
            - text: "To strengthen your skills and validate your expertise, pursue the official:"
            - text: "[👉 GitHub Actions Certification](https://learn.microsoft.com/en-us/credentials/certifications/github-actions/?practice-assessment-type=certification&wt.mc_id=continuousdelivery_wilcocontinuousdelivery_webpage_cnl)"
            - text: "Earn a verified credential from GitHub that demonstrates your ability to implement GitHub Actions in real-world CI/CD workflows. This certification page provides direct access to the required learning paths, skills modules, and the certification exam." 
      - actionId: finish_step
